packages/mongo/src/client/mongo-db.client.ts
packages/mongo/src/service/ensure-indexes.service.ts

Change loop of ensure index loop.
We were having a strange behavior with forEach

fix(@skore-io/mongo): ensure index loop

---

packages/health-check/README.md
packages/health-check/package.json

Documentation for the Health Check module.
So that its use is exemplified.

docs(@skore-io/health-check): readme

---

package-lock.json
package.json
packages/health-check/.gitignore
packages/health-check/tsconfig.build.json
packages/keycloack/.gitignore
packages/keycloack/.vscode/settings.json
packages/keycloack/README.md
packages/keycloack/jest.config.js
packages/keycloack/package-lock.json
packages/keycloack/package.json
packages/keycloack/src/index.ts
packages/keycloack/src/keycloack.module.ts
packages/keycloack/test/.eslintrc
packages/keycloack/test/module/keycloack.module.test.ts
packages/keycloack/tsconfig.build.json
packages/keycloack/tsconfig.json
packages/mongo/.gitignore
packages/mongo/jest.config.js
packages/mongo/test/mongo/module/test.module.ts
packages/mongo/tsconfig.build.json
packages/version/.gitignore
packages/version/tsconfig.build.json
tsconfig.build.json

Add Keycloack module scaffold
To provide a Keycloack lib

feat(@skore-io/keycloak): create package

---

packages/keycloak/README.md
packages/keycloak/src/client/index.ts
packages/keycloak/src/client/refresh-token.client.ts
packages/keycloak/src/index.ts
packages/keycloak/src/keycloak.module.ts
packages/keycloak/src/service/index.ts
packages/keycloak/src/service/logout.service.ts
packages/keycloak/src/service/refresh-token.service.ts
packages/keycloak/test/service/find-user.service.test.ts
packages/keycloak/test/service/refresh-token.service.test.ts

Export a service to refresh token of user in keycloak.
Because we need to generate a new access token when the current one expires.

feat(keycloak): refresh token

---

packages/keycloak/src/client/user-info.client.ts
packages/keycloak/src/service/check-resource-permission.service.ts
packages/keycloak/src/service/get-resource-permissions.service.ts
packages/keycloak/src/strategy/keycloak.strategy.ts
packages/keycloak/test/service/get-resource-permissions.service.test.ts

Improve errors in logs.
To facilitate debugging.

refactor(keycloak): improve errors

---

package-lock.json
packages/bull/README.md
packages/bull/package-lock.json
packages/bull/package.json
packages/bull/src/index.ts
packages/keycloak/src/client/user-info.client.ts
packages/keycloak/test/decorator/http.test.ts

Export bull methods.
To remove `bull` from skore-one and use these exported methods.

feat(bull): export bull methods

---

packages/keycloak/src/client/user-info.client.ts
packages/keycloak/src/strategy/keycloak.strategy.ts

Remove debug logs 
They are not necessary

refactor: remove logs

---

README.md
packages/google-auth/.eslintrc
packages/google-auth/.gitignore
packages/google-auth/.vscode/settings.json
packages/google-auth/README.md
packages/google-auth/jest.config.js
packages/google-auth/package-lock.json
packages/google-auth/package.json
packages/google-auth/src/decorator/google-auth.decorator.ts
packages/google-auth/src/decorator/index.ts
packages/google-auth/src/google-auth.module.ts
packages/google-auth/src/index.ts
packages/google-auth/src/strategy/google-auth.strategy.ts
packages/google-auth/src/strategy/index.ts
packages/google-auth/test/.eslintrc
packages/google-auth/test/config/.env
packages/google-auth/test/controller/controller.test.ts
packages/google-auth/tsconfig.build.json
packages/google-auth/tsconfig.json

`@skore-io/google-auth` package to validate request from google apis
We'll start to use pub sub push subscription and this integration sends a JWT in each request, this package helps to validate this tokens.

feat(google-auth): @GoogleAuth guard for pub sub push subscription

---

package-lock.json
packages/mongo/README.md
packages/mongo/package-lock.json
packages/mongo/package.json
packages/mongo/src/client/mongo-db.client.ts
packages/mongo/src/decorator/ensure-index.decorator.ts
packages/mongo/src/domain/constants.ts
packages/mongo/src/domain/index.ts
packages/mongo/src/domain/mongo-module.options.ts
packages/mongo/src/mongo.module.ts
packages/mongo/src/service/ensure-indexes.service.ts
packages/mongo/test/mongo/document/test.document.ts
packages/mongo/test/mongo/module/test.module.ts

Allow multiple database connections
Now we can have different database connections per module.

feat!: allow multiple databases

---

.eslintrc
package-lock.json
package.json
packages/bull/src/bull.module.ts
packages/bull/test/bull.module.test.ts
packages/google-auth/test/controller/controller.test.ts
packages/health-check/src/indicator/dependencies.indicator.ts
packages/health-check/test/controller/health.controller.test.ts
packages/health-check/test/indicator/dependencies.indicator.test.ts
packages/health-check/test/indicator/mongo.indicator.test.ts
packages/health-check/test/indicator/redis.indicator.test.ts
packages/keycloak/src/client/find-user.client.ts
packages/keycloak/src/client/user-info.client.ts
packages/keycloak/src/decorator/get-user.decorator.ts
packages/keycloak/src/domain/permission.domain.ts
packages/keycloak/src/domain/resource.domain.ts
packages/keycloak/src/errors/error.ts
packages/keycloak/src/service/create-resource.service.ts
packages/keycloak/src/service/find-resource-permissions.service.ts
packages/keycloak/src/service/find-resource.service.ts
packages/keycloak/src/service/get-resource-permissions.service.ts
packages/keycloak/test/.eslintrc
packages/keycloak/test/service/update-permission.service.test.ts
packages/mongo/src/mongo.module.ts
packages/mongo/src/service/ensure-indexes.service.ts
packages/pagination/src/pagination-response.ts

Fix lint warnings and errors.
:nail_care:

style: lint errors

---

packages/auth/src/decorator/is-admin-or-company.decorator.ts
packages/auth/src/strategy/admin-or-company.strategy.ts

Fix decorator rule
Because I forgot xD

fix: fix is-admin-or-company decorator rule

---

packages/auth/src/strategy/admin-or-company.strategy.ts

Fix validate method adding try catch
Because was wrong

fix(nestjs): adding try catch to method validate

---

package-lock.json
packages/google-auth/package-lock.json
packages/google-auth/package.json
packages/google-auth/src/decorator/google-auth.decorator.ts
packages/google-auth/src/google-auth.module.ts
packages/google-auth/src/guard/google-auth.guard.ts
packages/google-auth/src/guard/index.ts
packages/google-auth/src/index.ts
packages/google-auth/src/strategy/google-auth.strategy.ts

Add guard instead of using strategy directly.
To keep the pattern from other packages.

refactor(google-auth): add guard

---

.eslintrc
README.md
package-lock.json
packages/auth/package-lock.json
packages/auth/src/domain/user.domain.ts
packages/auth/test/base-test.ts

Retornando o campo `sessionId` na autenticação de um usuário
Porque o novo provisionador de conteúdos precisa do id de sessão de um usuário para o evento de conteúdo acessado

feat(user_domain): session_id

---

packages/auth/test/base-test.ts

Fix do lint no arquivo `base.test`
Para corrigir a execução desta [action](https://github.com/skore-io/nestjs-extensions/runs/6776764830?check_suite_focus=true)

fix(lint): auth base test

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum para evento de notificação criada;
- Pois teremos um evento para disparar após a notificação ser criada;

feat: add enum to event lib

---

packages/event/src/client/pub-sub.client.ts

corrigir forma de como ler a private key 
corrigir leitura da private key por env

fix(event): fix private key

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum à lib de eventos;
- Para conseguir mandar eventos de reindex_category através dela;

feat: add reindex category to enum

---

packages/event/src/enum/pub-sub.enum.ts

- Muda o type do evento;
- Para se adequar à nossa nomenclatura;

fix: event type

---

packages/event/README.md
packages/google-auth/README.md
packages/google-auth/src/service/authed-request.service.ts

Adicionando suporte para a criação de `google token` sem precisar do json de service account dentro do projeto.
Para poder utilizar em lambdas.

feat(authed_request): support envs and service account file

---

packages/google-auth/README.md
packages/google-auth/src/service/authed-request.service.ts

Corrige readme e adiciona await em função async.
Para que a lib funcione.

fix: add await to promise

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona type e action;
Para mandar em `messaging`;

feat: add type and action

---

.vscode/settings.json
packages/event/README.md
packages/event/package-lock.json
packages/event/package.json
packages/event/src/client/pub-sub.client.ts
packages/event/src/interface/client.interface.ts
packages/event/src/service/event.service.ts
packages/event/src/service/index.ts
packages/event/src/service/send-event.service.ts
packages/event/test/service/send-event.service.test.ts

- Adiciona um método para enviar eventos em batch;
Para enviarmos eventos em batch em `notifications`;

feat: add publish event in batch

---

packages/event/src/client/pub-sub.client.ts

- Conserta o máximo de mensagens;
Para ficar igual ao length do array;

fix: max messages

---

packages/event/src/client/pub-sub.client.ts

- Roda a execução de eventos em batches em paralelo;
Pois estava rodando sequencialmente (como a maldita doc do Google sugeria);

fix: add parallel execution

---

packages/pagination/src/pagination.type.ts

Adicionado type para lib de paginação.
Para facilitar o desenvolvedor que usa a lib tipar as props skipe and take

feat(pagination): add type pagination

---

packages/event/src/enum/pub-sub.enum.ts

Adicionando novo enum para utilização na libe de events para o client pub sub
Necessário a criação do enum para contemplar a task https://qulturerocks.atlassian.net/browse/LR-1452?atlOrigin=eyJpIjoiNzA0NTgxYzg1ODM4NDUxMDg4NmViZWMwZjViZjJjMTEiLCJwIjoiaiJ9
[
](https://qulturerocks.atlassian.net/browse/LR-1453?atlOrigin=eyJpIjoiZGQyMGY0NDY2NjI2NDg0MjhjY2UxMDczY2RjNmJhYjAiLCJwIjoiaiJ9)

chore(event):  add new enum

---

packages/pagination/src/pagination.type.ts

Adicionando novo type para resultado de uma determinada paginação.
Para facilitar o dia dia de quem precisa "tipar" o resultado de uma paginação.

chore(pagination): add result type

---

packages/bull/src/bull.module.ts
packages/bull/src/domain/bull-options.domain.ts

Ajustando o parâmetro que define o path do Bull Board.
No [PR anterior](https://github.com/skore-io/nestjs-extensions/pull/96) eu adicionei um path completo, mas precisamos apenas do base path.

fix(bull): bull board base path

---

packages/bull/src/index.ts

- Export onQueueCompleted event listener
- Necessário para implementacao de handler  no skore mission import

chore(bull): export onQueueCompleted event listener

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum;
Para termos o enum do comando de deletar sessões;

feat: add delete sessions enum

---

packages/event/src/enum/pub-sub.enum.ts

Atualizar enums
Para utlizar na solução para presença em massa.

chore(event): update enums

---

package.json

Altera a versão do _lerna_.
Corrigir erro no CI/CD.

chore: set lerna version

---

package-lock.json

Corrige a versão do lerna.
Corrigir erro no CI/CD.

fix: change lerna version

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum;
Pois preciso;

feat: add action enum

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona actions usadas pelo projeto `user`;
Pois preciso;

feat: add missing actions

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum leader_added nas actions do PubSub;
Pois passaremos a enviar o evento de associação de líder à um usuário;

feat: add leader_added enum

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona action para líder removido;
Porque eu esqueci no PR anterior :man_facepalming:

feat: add leader_removed action enum

---

packages/event/src/enum/pub-sub.enum.ts

Adicionar tipo de evento para convites `io.skore.events.invitation`.
Precisamos de um tipo de evento para utilizar em convites.

feat(event): add type event

---

packages/event/src/enum/pub-sub.enum.ts

Adicionar enum para ação de time removido.
Ao desvincular um time do usuário, é essencial executar uma ação coerente com a operação realizada.

feat(event): add team removed

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum ao PubSub;
Pois vamos começar a registrar logs de admin (eventos) associados à gestão de seções;

feat: add PubSub enum

---

packages/event/src/enum/pub-sub.enum.ts

Adicionar enum para ação de matrícula em massa.
Para utilizar no evento de criação de matrícula em massa.

feat(event): add bulk create enum

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enum para criação de bulk_enrollment;
Para enviarmos o evento pela lib, no projeto de missões;

feat: add bulk_enrollment_mission action

---

packages/event/src/enum/pub-sub.enum.ts

Adicinar enum de ação para inscrição em cursos presenciais.
Precisamos de um enum para a `action` do evento de inscrição em cursos presenciais.

feat(event): add action enum

---

.github/PULL_REQUEST_TEMPLATE.md
packages/event/src/enum/pub-sub.enum.ts

- Mapeia o evento de feedback form e a action de `answered`;
- Atualiza o PULL_REQUEST_TEMPLATE com a logo do Jira;
- Porque passaremos a disparar eventos desse tipo;
- Porque estamos utilizando o Jira agora e não mais o Asana;
---

feat(pub_sub_enum): map feedback form event and action

---

README.md
packages/auth/src/client/workspace.client.ts
packages/auth/src/domain/company.domain.ts
packages/auth/src/domain/user.domain.ts
packages/auth/src/util/index.ts
packages/auth/src/util/transformer.util.ts
packages/auth/test/strategy/admin-or-company.strategy.test.ts
packages/auth/test/strategy/company.strategy.test.ts

Adicionando métodos ao dominio do `User` para verificar a role.
Vai ficar mais elegante comparado a maneira que fazemos atualmente:

feat(user): add methods to check user role

---

packages/auth/src/client/workspace.client.ts
packages/auth/src/domain/user.domain.ts

Adicionando a propriedade `token` no user.
Alguns projetos usam essa info.

feat(user): enrich user with token

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona enums de missão;
Pois não temos.

feat: add mission enums

---

packages/event/src/enum/pub-sub.enum.ts

Adiciona o tipo de evento `'io.skore.commands.content'` no `PubSubTypeEventEnum` e a ação `delete_consume` no `PubSubActionEnum`.
Para ser usado nos comandos de exclução de consumo.

feat(event): add new command

---

packages/event/src/enum/pub-sub.enum.ts

Adiciona a ação `reset_worksheet` no `PubSubActionEnum`.
Para ser usado nos comando de _reset_ de _worksheet_ (quem diria).

feat(event): add reset worksheet action

---

packages/event/src/enum/pub-sub.enum.ts

Adiciona a ação `reset_scorm` no `PubSubActionEnum`.
Para ser usado nos comando de _reset_ de matrículas no _scorm_.
---

feat(event): add reset scorm enrollment action

---

packages/event/src/enum/pub-sub.enum.ts

Remove a `action` e o `type` antigo de eventos de formulário de feedback.
Por que eles não serão mais utilizados dando lugar aos novos inseridos no PR https://github.com/skore-io/nestjs-extensions/pull/137
---

feat(enum): remove old feedback type and action

---

packages/bull/README.md
packages/bull/src/bull.module.ts
packages/bull/src/domain/bull-options.domain.ts

Adicionado modo cluster para bull
Para suportar a redis cluster
---

feat: bull cluster

---

package-lock.json
package.json
packages/auth/src/service/authed-request.service.ts

Add cache para guardar token 
Para não precisar bater novamente no keycloak e assim resolver alguns problemas de status 502 no nosso ambiente
---

feat: add cache

---

packages/event/src/enum/pub-sub.enum.ts

add novo enum na lib de eventos 
pq não tem esse enum ainda

chore(event): update event

---

package-lock.json
packages/auth/package.json

Instalando a lib `qs` no pacote de **auth**.
Projetos que não possuem essa lib instalada estão com problema na build.

fix(auth): install qs package

---

packages/event/src/client/pub-sub.client.ts

Adicionando o tópico events v2 no método `publishInBatch`.
Esse método é usado pelo MEDUSA para enviar eventos e vamos migrar para v2.

chore(event): add events-v2 topic

---

packages/event/src/client/pub-sub.client.ts

Adicionando o tópico events v2 no método `publishEventsInBatch` e removendo do `publishInBatch`.
No PR https://github.com/skore-io/nestjs-extensions/pull/144 adicionamos errado rsrs

chore(event): add events-v2 topic to publish events in batch

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona types externos;
Para podermos receber eventos externos através da aplicação event-manager... que faz uso dessa lib para tipar/validar os eventos;

feat: add external types

---

packages/event/src/client/pub-sub.client.ts

- Usa a cold-events subscription;
Para matarmos a assinatura events-v2;

feat: use cold events subscription

---

packages/event/src/enum/pub-sub.enum.ts

fix: add action on enum

---

packages/event/src/enum/pub-sub.enum.ts

- Add a action impersonation_ended action;
Para termos mapeada;

feat: add impersionation_ended action

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona tipos de eventos do Rails;
Para migrarmos para o novo tópico de cold-events;

feat: add missing types enum

---

packages/event/src/client/pub-sub.client.ts

- Manda os eventos em batch para o tópico cold;
Para migrarmos para a nova infraestrutura de eventos;

feat: send batch to cold_events topic

---

packages/event/src/enum/pub-sub.enum.ts

fix: add missing enum

---

packages/event/src/enum/pub-sub.enum.ts

feat: add recycled action

---

packages/event/src/enum/pub-sub.enum.ts

Adicionado novo `PubSubActionEnum` referente a criação de certificado em missões
Usarmos no projeto de auditoria para emitir um comando para criação de certificado
---

feat(pub_sub_action): create mission certificate

---

packages/event/src/enum/pub-sub.enum.ts

Adicionado ação de remoção de presença
Informar que estamos removendo uma presença de usuário em uma `live class`
---

feat(event_action): remove attendance

---

packages/event/src/enum/pub-sub.enum.ts

- Adiciona novas actions;
Porque apesar de estarem no Rails passam pelo event-manager, e lá utilizamos a lib;

feat: add actions

---

README.md
docker-compose.yml
package-lock.json
packages/asset/.gitignore
packages/asset/README.md
packages/asset/jest.config.js
packages/asset/package.json
packages/asset/src/asset.module.ts
packages/asset/test/dummy.test.ts
packages/asset/tsconfig.build.json
packages/asset/tsconfig.json
packages/auth/src/auth.module.ts
packages/auth/test/client/keycloak.client.test.ts
packages/auth/test/service/authed-request.service.test.ts
packages/event/test/service/event.service.test.ts

Adicionando lib `@skore-io/asset`.
Vamos usar essa lib para fazer a gestão de arquivos no Cloudinary e AWS S3.
Esse PR é apenas a criação do módulo. 
No próximo PR irei criar os métodos de upload, get, delete, etc

chore: add asset lib

---

packages/asset/jest.config.js
packages/asset/package.json
packages/asset/src/asset.module.ts
packages/asset/src/client/cloudinary.client.ts
packages/asset/src/client/index.ts
packages/asset/src/client/s3.client.ts
packages/asset/src/enum/asset-client.enum.ts
packages/asset/src/enum/index.ts
packages/asset/src/interface/asset-client.interface.ts
packages/asset/src/interface/index.ts
packages/asset/test/asset.module.unit.test.ts
packages/asset/test/dummy.test.ts
packages/asset/test/test.module.ts
packages/asset/test/unit/client/cloudinary.client.unit.test.ts
packages/asset/test/unit/client/s3.client.unit.test.ts

Adicionando estrutura da lib `@skore-io/asset` para começarmos a desenvolver os métodos.
Estrutura da lib que será usada para upload de arquivos para o `Cloudinary` e `S3`.
No próximo PR vou adicionar implementação ao método `upload` e um README explicando como usar a lib.

build(asset): add structure

---

packages/asset/src/client/cloudinary.client.ts
packages/asset/src/client/s3.client.ts
packages/asset/src/index.ts
packages/asset/src/interface/asset-client.interface.ts
packages/asset/src/type/index.ts
packages/asset/src/type/upload-response.type.ts
packages/asset/test/unit/client/cloudinary.client.unit.test.ts
packages/asset/test/unit/client/s3.client.unit.test.ts

Adicionando upload de arquivos para o cloudinary.
Vamos usar essa lib para gestão de arquivos.

feat(asset): upload to cloudinary
