skore-io/nestjs-extensions

docker-compose.yml
packages/health-check/.env
packages/health-check/src/health-check.module.ts

Pass redis password
Our staging/production redis instances uses passwords

fix(health-check): use redis password config

---

packages/pagination/src/pagination-args.ts
packages/pagination/test/pagination-args.test.ts

Use default values to pagination `take` when:
- The value is greater than **MAX_TAKE**;
- The value is smaller than **MIN_TAKE**.
Because we think that throwing an error to the user is not a good experience.

refactor(pagination): use default values to pagination take

---

packages/pagination/jest.config.js
packages/pagination/src/pagination-args.ts
packages/pagination/src/pagination.ts
packages/pagination/test/pagination-args.test.ts
packages/pagination/test/pagination.test.ts

- Remove `Min` and `Max` validations from **pagination-args**;
- Move the default values logic to the `pagination class`, because the `pagination args` represent only the **graphql** parameters.
To keep the pagination rules in `pagination class`.

refactor(pagination): remove validations from args

---

packages/keycloak/src/keycloak.module.ts

exports delete resource service
so we can use it outside the lib

fix: exports DeleteResourceService

---

packages/keycloak/src/domain/user.domain.ts
packages/keycloak/test/service/find-user.service.test.ts

BREAKING CHANGE: organizationId removed from user
Rename organization to environment
To met architectural design

refactor!: rename organization to environment

---

packages/mongo/.env
packages/mongo/src/client/mongo-db.client.ts
packages/mongo/src/domain/constants.ts
packages/mongo/src/domain/index.ts
packages/mongo/src/domain/mongo-module.options.ts
packages/mongo/src/mongo.module.ts
packages/mongo/test/mongo/module/test.module.ts

Create one `Db` instance provider for each module register
To support `skore-one` with multiple `extensions` and each one access a different database with it's own credentials

refactor(mongo): support multiple module connections

---

package.json
packages/pagination/package.json

Adjust `class-transformer` version.
We had the same problem in other project, fixed in [this PR](https://github.com/skore-io/skore-one-extension-evaluation/pull/19).

fix: class-transformer version

---

packages/keycloak/realm.json
packages/keycloak/src/domain/index.ts
packages/keycloak/src/domain/resource.domain.ts
packages/keycloak/src/domain/scope-type.domain.ts
packages/keycloak/src/service/check-resource-permission.service.ts
packages/keycloak/src/service/get-resource-permissions.service.ts
packages/keycloak/test/factory/policy.factory.ts
packages/keycloak/test/service/check-resource-permission.service.test.ts
packages/keycloak/test/service/get-resource-permissions.service.test.ts

Change the keycloak permission scopes.
Because we will not have such granular permission.

refactor(keycloak): change permission scopes

---

packages/keycloak/src/domain/permission.domain.ts
packages/keycloak/src/service/create-permission.service.ts
packages/keycloak/test/service/create-permission.service.test.ts

Receive `resource name` in create permission method, and search `resource id`.
Because we don't have the `resource id` in skore-one.

refactor(keycloak): search resource id to create permission

---

packages/keycloak/src/errors/error.ts
packages/keycloak/src/errors/index.ts
packages/keycloak/src/service/update-permission.service.ts
packages/keycloak/test/service/update-permission.service.test.ts

Retruns an unpeocessable entity error when keycloak returns 500
To help client to handle the error

feat: handle 500 when updating permission

---

package-lock.json
packages/bull/.env
packages/bull/README.md
packages/bull/package-lock.json
packages/bull/package.json
packages/bull/src/bull.module.ts
packages/bull/src/domain/bull-options.domain.ts
packages/bull/test/module/test.module.ts

- Bump `bull-board` because the current package has been deprecated;
- Change the redis payload because in `nestjs/bull@0.4.2` no longer accepts a string :/
:rocket:

feat(bull): bump bull-board

---

packages/auth/src/decorator/current.decorator.ts
packages/auth/src/decorator/index.ts
packages/auth/src/domain/index.ts
packages/auth/src/domain/user-or-company.domain.ts
packages/auth/src/strategy/admin-or-company.strategy.ts
packages/auth/test/strategy/admin-or-company.strategy.test.ts

- Adds a decorator named `Current` to fetch user or company in the request;
- Because both user or company were being added into `req.user`, which is semantically wrong, considering we separate user and companies in the lib;
- I've chosen only `Current` as the decorator name to fetch it, but I am open to suggestions of better names;

feat: add auth current decorator

---

packages/event/README.md
packages/event/src/client/pub-sub.client.ts
packages/event/src/enum/pub-sub.enum.ts
packages/event/src/error/coded.error.ts
packages/event/src/error/publish-pub-sub.error.ts
packages/event/src/error/validation-attribute.error.ts
packages/event/test/client/pub-sub.client.test.ts

Necessidade de usar a lib envio de evento através da lambda notification_find_target
- atualização do enum de actions necessária para o uso na lambda mencionada. 
- remover pacote do framework nest (cammon) e assim poder usar em qualquer projeto javascript/typscript.

fix(event): remove common dependency and update enum

---

packages/event/src/client/pub-sub.client.ts

Fix para usar a lib de eventos sem precisar do json de service account dentro do projeto.
Para poder ter pricipalmente a utilização em uma lambda.

fix(event): fix auth in google auth

---

packages/event/src/client/pub-sub.client.ts
packages/event/test/client/pub-sub.client.test.ts

Fix para alterar camelcase para snake_case
os eventos que são publicados pela lib estão ficando com o created_at em camelcase, e isso está gerando problemas nos relatorios.

fix(event): change camel case createAt to snake case

---

packages/event/src/client/pub-sub.client.ts

- Resolve o milli seconds;
Para não demorar o envio do batch;

fix: max milli seconds

---

packages/event/src/enum/pub-sub.enum.ts

Necessidade de atualizar enums da lib de eventos.
Para ser utilizado na solução de inscrição em massa.

chore(event): add news enums to feature live course

---

packages/auth/src/client/workspace.client.ts

Utiliza o domain correto do workspace;
Pois o /api aponta para um API Gateway diferente... que queremos deprecar;

fix: use correct workspace domain

---

packages/event/src/enum/pub-sub.enum.ts

Adicionar `enum` para evento de batch.
Adicionamos um novo evento ao criar batch no projeto de user, com isso precisamos de um enum correspondente.
Any: [PR com o novo evento](https://github.com/skore-io/user/pull/275)

feat(event): add pub-sub enum

---

packages/event/README.md
packages/event/src/client/pub-sub.client.ts
packages/event/src/index.ts
packages/event/src/interface/client.interface.ts
packages/event/src/service/event.service.ts
packages/event/src/type/event-attributes.type.ts
packages/event/src/type/index.ts
packages/event/src/type/pubsub-event.type.ts
packages/event/test/client/pub-sub.client.test.ts
packages/event/test/service/send-event.service.test.ts

Adicionando método que publica mensagens em batch no PubSub.
Estamos criando um enviador de eventos em batch para ser usado pelo nosso time interno.
Existe um método semelhante que envia vários eventos do mesmo contexto. Os atributos não mudam, apenas o body. Marquei ele como depreciado e removi das docs para que ninguém mais o use. O ideal é usarmos o método `publishInBatch` a partir de agora.

feat(event): publish in batch

---

packages/event/src/enum/pub-sub.enum.ts

Adicionar enum `canceled` para utilizar no evento de cancelamento de um convite.
Devemos implementar um enum que represente a ação de um cancelamento de convite.

feat(event): add enum canceled

---

packages/event/src/enum/pub-sub.enum.ts

Adiciona o evento `io.skore.events.space.team` no `PubSubTypeEventEnum`.
Para ser usado nos eventos de log de edição de vínculo entre time e espaço.

feat(event): add new event

---

packages/event/src/service/event.service.ts

- Adiciona um método específico para enviar para um tópico diferente;
Pois podemos causar problemas de loop infinito caso falte a url, utilizando o método anterior. Pois sempre cairia no tópico de eventos, e com os novos triggers do mongo, isso pode gerar um loop infinito;

feat: different method to send to topic

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

Atualizando o github actions para `v4`.
Remover os warnings do CI/CD.

ci: bump git actions to v4

---

README.md
packages/schema/src/script/copy-to-dist.script.ts

Copiando todas as pastas de interfaces para o `/dist`.
As interfaces não estavam sendo copiadas para o `/dist`.
Quebrei isso no PR: https://github.com/skore-io/nestjs-extensions/pull/149

fix(schema): write interfaces to dist

---

packages/event/src/client/pub-sub.client.ts
packages/event/test/client/pub-sub.client.test.ts

- Adiciona retry para o envio do evento ao Pub/Sub;
Pegamos alguns casos em que a chamada ao Pub/Sub simplesmente falha. Dessa forma, pensamos em adicionar um retry a nível de código caso aconteça algum erro;

feat: add publish retry

---

packages/event/src/enum/pub-sub.enum.ts

- Adicionar enum para eventos da audiência do game `io.skore.events.game.audience`
Para utilizar na criação de logs no mongo.
---

feat(pub_sub_type_event): add enum game audience

---

.github/workflows/main.yml
lerna.json
package.json
packages/auth/package.json

Ajustando o commit da release para seguir o formato: `chore(package_name): package_version`, usando o nome do pacote que foi atualizado e a nova versão.
Exemplo: `chore(@skore-io/auth): 1.19.12`
Estavamos gerando um commit sem informações após release, conforme imagem do print.

fix(lerna): release version
